docker_sandbox_dev/Models/ErrorViewModel.cs
using System;

namespace docker_sandbox_dev.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

docker_sandbox_dev/Models/Sandbox.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace docker_sandbox_dev.Models
{
    public enum SandboxStatus
    {
        Started,
        Stopped
    }
    public class Sandbox
    {
        public Guid Id { get; set; }
        public string Port { get; set; }
        public SandboxStatus Status { get; set; }
    }
}

docker_sandbox_dev/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using docker_sandbox_dev.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace docker_sandbox_dev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task Login(string returnUrl = null)
        {
            if (returnUrl == null)
                returnUrl = "/";
            if (User.Identity == null || !User.Identity.IsAuthenticated)
            {
                AuthenticationProperties props = new AuthenticationProperties
                {
                    RedirectUri = returnUrl,
                    Items =
                        {
                            { "scheme", "oidc" },
                            { "returnUrl", returnUrl }
                        }
                };
                await HttpContext.ChallengeAsync(props);
            }
        }

        [Authorize]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
        }

        [Authorize]
        public IActionResult Privacy()
        {
            AuthenticateResult ttt = this.HttpContext.AuthenticateAsync().Result;
            ViewData["Message"] = "Secure page.";

            return View();
        }

        public async Task<IActionResult> CreateSandbox()
        {
            string accessToken = await this.HttpContext.GetTokenAsync("access_token");

            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = await client.PostAsync("http://localhost:5003/api/sandbox", new StringContent(""));

            if (response.IsSuccessStatusCode)
            {
                string containerId = await response.Content.ReadAsStringAsync();
                Console.WriteLine(containerId);
                response = await client.PostAsync("http://localhost:5003/api/sandbox/start/" + containerId, new StringContent(""));
                string responseJson = await response.Content.ReadAsStringAsync();
                Console.WriteLine(responseJson);
                Sandbox sandbox = JsonConvert.DeserializeObject<Sandbox>(responseJson);
                if (response.IsSuccessStatusCode)
                {
                    return View("ide", sandbox);
                }
                else
                {
                    ViewBag.Json = await response.Content.ReadAsStringAsync();
                }
            }
            else
            {
                ViewBag.Json = "403 - Forbidden";
            }


            return View("json");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

docker_sandbox_dev/Controllers/SandboxController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace docker_sandbox_dev.Controllers
{
    public class SandboxController : Controller
    {
        public IActionResult ReturnToIndex()
        {
            return Redirect("/");
        }

        [Authorize]
        public async Task<IActionResult> Delete(Guid sandboxId)
        {
            string accessToken = await this.HttpContext.GetTokenAsync("access_token");

            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = await client.DeleteAsync("http://localhost:5003/api/sandbox/" + sandboxId);

            if (response.IsSuccessStatusCode)
            {

            }
            return Redirect("/");
        }

        [Authorize]
        public async Task<IActionResult> Start(Guid sandboxId)
        {
            string accessToken = await this.HttpContext.GetTokenAsync("access_token");

            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = await client.PostAsync("http://localhost:5003/api/sandbox/start/" + sandboxId, new StringContent(""));

            if (response.IsSuccessStatusCode)
            {

            }
            return Redirect("/");
        }

        [Authorize]
        public async Task<IActionResult> Stop(Guid sandboxId)
        {
            string accessToken = await this.HttpContext.GetTokenAsync("access_token");

            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = await client.PostAsync("http://localhost:5003/api/sandbox/stop/" + sandboxId, new StringContent(""));

            if (response.IsSuccessStatusCode)
            {

            }
            return Redirect("/");
        }
    }
}

docker_sandbox_dev/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Authentication
@{
    ViewData["Title"] = "Home Page";
}

<h2>lala</h2>
@if (User.Identity.IsAuthenticated)
{
    @*<partial name="SandboxList.cshtml" />*@
    @await Html.PartialAsync("SandboxList.cshtml");
}

docker_sandbox_dev/Views/Home/SandboxList.cshtml
@using Microsoft.AspNetCore.Authentication;
@using System.Net.Http;
@using System.Net.Http.Headers;
@using Newtonsoft.Json;
<html>
<head>
    <style>
        .box {
            float: left;
            height: 20px;
            width: 20px;
            margin-bottom: 15px;
            border: 1px solid black;
            clear: both;
        }

        .red {
            background-color: red;
        }

        .green {
            background-color: green;
        }

        .blue {
            background-color: blue;
        }
    </style>
</head>
<body>
    @{
        if (User.Identity.IsAuthenticated)
        {
            List<Sandbox> Sandboxes = null;
            string accessToken = await this.Context.GetTokenAsync("access_token");

            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            HttpResponseMessage response = await client.GetAsync("http://localhost:5003/api/sandbox");

            if (response.IsSuccessStatusCode)
            {
                string sandboxesJson = response.Content.ReadAsStringAsync().Result;
                Sandboxes = JsonConvert.DeserializeObject<List<Sandbox>>(sandboxesJson);
            }
            if (Sandboxes != null)
            {
                foreach (var sb in Sandboxes)
                {
                    <form method="post">
                        <span>@sb.Id.ToString()</span>
                        @if (sb.Status == SandboxStatus.Stopped)
                        {
                            <div class='box red' />
                        }
                        else
                        {
                            <div class='box green' />
                        }
                        <input type="hidden" name="sandboxId" id="sandboxId" value="@sb" />
                        <button asp-controller="Sandbox" asp-action="Start">Start</button>
                        <button asp-controller="Sandbox" asp-action="Stop">Stop</button>
                        <button asp-controller="Sandbox" asp-action="Delete"> Delete</button>
                    </form>
                }
            }
        }
    }
</body>
</html>

docker_sandbox_dev/Views/Home/forbidden.cshtml
@{
    ViewData["Title"] = "403 - Forbidden";
}
<pre>@ViewBag.Json</pre>

docker_sandbox_dev/Views/Home/ide.cshtml
@model Sandbox
@{
    ViewData["Title"] = "IDE";
}

@{
    string url = "http://localhost:" + @Model.Port;
}

<a href="@url" target="_blank" rel="noopener noreferrer">Link</a>

docker_sandbox_dev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="CallAPI">CallAPI</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coffee" asp-action="Index">Coffee</a>
                        </li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

docker_sandbox_dev/Views/Shared/json.cshtml
@{
    ViewData["Title"] = "json";
}
<pre>@ViewBag.Json</pre>